import villa1 from "../assets/images/villa1.jpg";
import villa2 from "../assets/images/villa2.jpg";
import villa3 from "../assets/images/villa3.jpg";
import apartment1 from "../assets/images/apartment1.jpg";
import apartment2 from "../assets/images/apartment2.jpg";
import apartment3 from "../assets/images/apartment3.jpg";
import office1 from "../assets/images/office1.jpg";
import office2 from "../assets/images/office2.jpg";
import office3 from "../assets/images/office3.jpg";
import bungalow1 from "../assets/images/bungalow1.jpg";
import bungalow2 from "../assets/images/bungalow2.jpg";
import bungalow3 from "../assets/images/bungalow3.jpg";
import glasshouse1 from "../assets/images/glasshouse1.jpg";
import glasshouse2 from "../assets/images/glasshouse2.jpg";
import bedsitter1 from "../assets/images/bedsitter1.jpg";
import bedsitter2 from "../assets/images/bedsitter2.jpg";
import onebedroom1 from "../assets/images/onebedroom1.jpg";
import onebedroom2 from "../assets/images/onebedroom2.jpg";
import singleroom1 from "../assets/images/singleroom1.jpg";
import singleroom2 from "../assets/images/singleroom2.jpg";

const properties = [
  {
    id: 1,
    name: "Serene Villa",
    price: 150000,
    county: "Nairobi",
    rooms: 6,
    beds: 4,
    image: villa1,
    property: "Villa",
    description: "Luxury villa available for monthly rental.",
  },
  {
    id: 2,
    name: "Greenview Apartments",
    price: 35000,
    county: "Mombasa",
    rooms: 3,
    beds: 2,
    image: apartment1,
    property: "Apartment",
    description: "Modern apartment available for monthly rental.",
  },
  {
    id: 3,
    name: "Silverwood Office Suites",
    price: 80000,
    county: "Kisumu",
    rooms: 5,
    beds: 0,
    image: office1,
    property: "Office",
    description: "Spacious office space available for monthly rental.",
  },
  {
    id: 4,
    name: "Palm Beach Bungalow",
    price: 120000,
    county: "Kwale",
    rooms: 4,
    beds: 3,
    image: bungalow1,
    property: "Bungalow",
    description: "A stylish bungalow available for monthly rental.",
  },
  {
    id: 5,
    name: "Skyview Glasshouse",
    price: 25000,
    county: "Nakuru",
    rooms: 2,
    beds: 1,
    image: glasshouse1,
    property: "Glasshouse",
    description: "A scenic glasshouse available as a guest house on a daily basis.",
  },
  {
    id: 6,
    name: "Urban Bed Sitter",
    price: 15000,
    county: "Kiambu",
    rooms: 1,
    beds: 1,
    image: bedsitter1,
    property: "Bed Sitter",
    description: "Affordable bed sitter available for monthly rental.",
  },
  {
    id: 7,
    name: "Prestige One Bedroom",
    price: 25000,
    county: "Machakos",
    rooms: 2,
    beds: 1,
    image: onebedroom1,
    property: "One Bedroom",
    description: "Spacious one-bedroom available for monthly rental.",
  },
  {
    id: 8,
    name: "Tranquil Single Room",
    price: 8000,
    county: "Uasin Gishu",
    rooms: 1,
    beds: 1,
    image: singleroom1,
    property: "Single Room",
    description: "Budget single room available for monthly rental.",
  },
  {
    id: 9,
    name: "Seaside Villa",
    price: 180000,
    county: "Kilifi",
    rooms: 5,
    beds: 4,
    image: villa2,
    property: "Villa",
    description: "Luxury seaside villa available for monthly rental.",
  },
  {
    id: 10,
    name: "Horizon Apartments",
    price: 30000,
    county: "Nyeri",
    rooms: 3,
    beds: 2,
    image: apartment2,
    property: "Apartment",
    description: "Modern apartment available for monthly rental.",
  },
  {
    id: 11,
    name: "Summit Office Park",
    price: 120000,
    county: "Eldoret",
    rooms: 6,
    beds: 0,
    image: office2,
    property: "Office",
    description: "Premium office space available for monthly rental.",
  },
  {
    id: 12,
    name: "Sunset Bungalow",
    price: 95000,
    county: "Laikipia",
    rooms: 4,
    beds: 3,
    image: bungalow2,
    property: "Bungalow",
    description: "Scenic bungalow available for monthly rental.",
  },
  {
    id: 13,
    name: "Mountain View Glasshouse",
    price: 27000,
    county: "Narok",
    rooms: 2,
    beds: 1,
    image: glasshouse2,
    property: "Glasshouse",
    description: "A beautiful glasshouse available as a guest house on a daily basis.",
  },
  {
    id: 14,
    name: "City Bed Sitter",
    price: 18000,
    county: "Kajiado",
    rooms: 1,
    beds: 1,
    image: bedsitter2,
    property: "Bed Sitter",
    description: "Spacious bed sitter available for monthly rental.",
  },
  {
    id: 15,
    name: "Cosy One Bedroom",
    price: 28000,
    county: "Bungoma",
    rooms: 2,
    beds: 1,
    image: onebedroom2,
    property: "One Bedroom",
    description: "Comfortable one-bedroom available for monthly rental.",
  },
  {
    id: 16,
    name: "Downtown Single Room",
    price: 7000,
    county: "Busia",
    rooms: 1,
    beds: 1,
    image: singleroom2,
    property: "Single Room",
    description: "Affordable single room available for monthly rental.",
  },
  {
    id: 17,
    name: "Royal Villa",
    price: 200000,
    county: "Meru",
    rooms: 6,
    beds: 5,
    image: villa3,
    property: "Villa",
    description: "Luxury royal villa available for monthly rental.",
  },
  {
    id: 18,
    name: "Palm View Apartments",
    price: 32000,
    county: "Kericho",
    rooms: 3,
    beds: 2,
    image: apartment3,
    property: "Apartment",
    description: "Modern apartment available for monthly rental.",
  },
  {
    id: 19,
    name: "Elite Office Tower",
    price: 100000,
    county: "Tharaka Nithi",
    rooms: 5,
    beds: 0,
    image: office3,
    property: "Office",
    description: "High-end office space available for monthly rental.",
  },
  {
    id: 20,
    name: "Lush Green Bungalow",
    price: 110000,
    county: "Siaya",
    rooms: 4,
    beds: 3,
    image: bungalow3,
    property: "Bungalow",
    description: "Serene bungalow available for monthly rental.",
  }
];

export default properties;
